### ISSUE TITLE
Have a bug when running the script

### ISSUE THREAD

**Issue by r1ce-m** [ash09/angr-static-analysis-for-vuzzer64#1]
I installed everything successfully and run the script with Lava-M base64 binary.
This is what I got from running. Any idea why this happened?
Thanks in advance for your help.

Traceback (most recent call last):
  File "BB-weight-angr.py", line 272, in <module>
    calculate_weight_edges(cfg_f)
  File "BB-weight-angr.py", line 44, in calculate_weight_edges
    cfg.graph.edge[node][s]['weight'] = weight
AttributeError: 'DiGraph' object has no attribute 'edge'

**Comment by ghost** [comment]
I fixed this bug by downgrading networkx to an older Version via `pip install "networkx<2.0"` but then another error occurs which I don't know how to fix.

Traceback (most recent call last):
  File "angr-static-analysis-for-vuzzer64-master/BB-weight-angr.py", line 273, in <module>
    calculate_weight_blocks(cfg_f)
  File "angr-static-analysis-for-vuzzer64-master/BB-weight-angr.py", line 62, in calculate_weight_blocks
    current_node.weight = 1.0
AttributeError: 'CFGNodeA' object has no attribute 'weight'

**Comment by george-kuanli-peng** [comment]
I have made some code changes to make it work with `Angr 7.8.9.26` and `NetworkX 2.1`, which should hopefully fix the problems mentioned by @natalie13m and @Speksify. More details could be found in pull request #2.
